In [1]:
import numpy as np
import pandas as pd
from ast import literal_eval
import gurobipy as gp
from gurobipy import quicksum
from gurobipy import GRB
import csv
import matplotlib.pyplot as plt
import ast

In [2]:
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

In [13]:
# df = pd.read_csv('onLastModelweUseR1.csv')
df = pd.read_csv('onLastModelweUseR2Level2.csv')
# df['resultsS2E2'][0]

In [14]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,HOUSEID,HHFAMINC,STRTTIME,ENDTIME,TRVLCMIN,TRPMILES,DWELTIME,CENSUS_D,WHYTRP1S_GENERAL,WHYFROM_GENERAL,states,public_charge,work_charge,max_j,Cluster_new_features,LowerLine,UpperLine,income_classes,public_avail_share,work_avail_share,public_charge_assign,work_charge_assign,power,ePrice,resultsS3E2,resultsS3E8,resultsS5E2,resultsS5E8
0,0,0,0,30000094,30000,"[740, 1340, 1420, 1705]","[755, 1405, 1438, 1715]","[15, 25, 18, 10]","[8.05, 5.883, 5.898, 4.864]","[345.0, 15.0, 147.0, 411.0]",9,"['Work', 'Work', 'Work', 'Home']","['Home', 'Work', 'Work', 'Work', 'Home']","['""\'Home\'""', ' "" \'Work\'""', ' "" \'Work\'""',...",1,1,5,2,36996,187706,0,0.330093,0.035370,1,0,"[6.0, 6.0, 6.0, 6.0, 6.0]","[0.118, 0.095, 0.095, 0.095, 0.118]","[1.0, 0.0, 0.19863636363636372, 0.0, 0.5435353...","[1.0, 0.0, 0.19863636363636372, 0.0, 3.5738383...","[-0.0, 0.0, 0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 2.762373737373738]"
1,1,1,1,30000095,62500,"[1000, 1140, 1230, 1415, 1600, 1700, 2000, 2330]","[1015, 1155, 1250, 1430, 1610, 1715, 2015, 2345]","[15, 15, 20, 15, 10, 15, 15, 15]","[1.926, 3.247, 3.896, 6.34, 1.226, 3.618, 3.64...","[75.0, 35.0, 85.0, 90.0, 50.0, 165.0, 195.0, 3...",3,"['Public', 'Public', 'Public', 'Public', 'Publ...","['Home', 'Public', 'Public', 'Public', 'Public...","['""\'Home\'""', ' "" \'Public\'""', ' "" \'Public\...",0,0,9,2,26319,108377,1,0.047394,0.007430,0,0,"[6.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0...","[0.136, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0....","[1.0, 0.10182424242424241, 0.0, 0.0, 0.0, 0.0,...","[1.0, 0.43591515151515153, 0.0, 0.0, 0.0295454...","[-0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]","[1.0, 0.3147030303030303, 0.0, 0.0, 0.0, 0.0, ..."
2,2,2,2,30000194,5000,"[930, 1230]","[1015, 1430]","[45, 120]","[8.312, 8.202]","[135.0, 582.0]",9,"['Public', 'Home']","['Home', 'Public', 'Home']","['""\'Home\'""', ' "" \'Public\'""', ' "" \'Home\'""']",0,0,3,1,37025,163205,0,0.330093,0.035370,0,0,"[6.0, 50.0, 6.0]","[0.118, 0.35, 0.118]","[1.0, 0.03947878787878788, 0.0]","[1.0, 0.4031151515151515, 0.0]","[-0.0, 0.0, 0.0]","[1.0, 0.28190303030303027, 0.0]"
3,3,3,3,30000227,62500,"[845, 1045]","[910, 1110]","[25, 25]","[9.105, 9.054]","[95.0, 774.0]",9,"['Public', 'Home']","['Home', 'Public', 'Home']","['""\'Home\'""', ' "" \'Public\'""', ' "" \'Home\'""']",0,0,3,2,36996,187706,1,0.330093,0.035370,0,0,"[6.0, 50.0, 6.0]","[0.118, 0.35, 0.118]","[1.0, 0.04944848484848484, 0.0]","[1.0, 0.41308484848484844, 0.0]","[-0.0, 0.0, 0.0]","[1.0, 0.2918727272727273, 0.0]"
4,4,4,4,30000309,87500,"[1400, 1445]","[1405, 1450]","[5, 5]","[1.688, 1.698]","[40.0, 570.0]",7,"['Public', 'Home']","['Home', 'Public', 'Home']","['""\'Home\'""', ' "" \'Public\'""', ' "" \'Home\'""']",1,1,3,2,26114,124754,1,0.036816,0.007882,0,0,"[6.0, 50.0, 6.0]","[0.112, 0.35, 0.112]","[-0.0, 0.0, 0.0]","[1.0, 0.32355151515151515, 0.0]","[-0.0, 0.0, 0.0]","[1.0, 0.20233939393939396, 0.0]"

In [12]:
# df['resultsS3E2'] = df['resultsS3E2'].str[1:-1].str.split(',').tolist()
# df['resultsS3E8'] = df['resultsS3E8'].str[1:-1].str.split(',').tolist()
# df['resultsS5E2'] = df['resultsS5E2'].str[1:-1].str.split(',').tolist()
# df['resultsS5E8'] = df['resultsS5E8'].str[1:-1].str.split(',').tolist()

In [ ]:
# Convert entire column to a list
# df["resultsS5E2"] = df["resultsS5E2"].apply(ast.literal_eval)

# df['resultsS3E2'] = df['resultsS3E2'].apply(lambda x: literal_eval(x))
# df['resultsS3E8'] = df['resultsS3E8'].apply(lambda x: literal_eval(x))
# df['resultsS5E2'] = df['resultsS5E2'].apply(lambda x: literal_eval(x))
# df['resultsS5E8'] = df['resultsS5E8'].apply(lambda x: literal_eval(x))

In [15]:
def deploy_or_not(x):
#     if type(x)==list:
#         if x[-1] > 0:
#             return 1
        return x[0]
#     else:
#         return 0

In [16]:
df['Cluster_new_features'] = df['Cluster_new_features'].astype('int')

In [17]:
cluster0 = df[df['Cluster_new_features'] == 0]
cluster1 = df[df['Cluster_new_features'] == 1]
cluster2 = df[df['Cluster_new_features'] == 2]

In [ ]:
# type(df.loc[0,'Cluster_new_features'])# == 2type(df.loc[0,'Cluster_new_features'])# == 2

In [18]:
cluster0S3E2 = cluster0[cluster0['resultsS3E2']!='infeasible']

In [19]:
cluster0S3E2.loc[:,'resultsS3E2'] = cluster0S3E2.loc[:,'resultsS3E2'].apply(lambda x: literal_eval(x))
cluster0S3E2['deployS3E2']=cluster0S3E2['resultsS3E2'].agg(deploy_or_not)
cluster0S3E2.head()

/Users/cheng_xi/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
/Users/cheng_xi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,HOUSEID,HHFAMINC,STRTTIME,ENDTIME,TRVLCMIN,TRPMILES,DWELTIME,CENSUS_D,WHYTRP1S_GENERAL,WHYFROM_GENERAL,states,public_charge,work_charge,max_j,Cluster_new_features,LowerLine,UpperLine,income_classes,public_avail_share,work_avail_share,public_charge_assign,work_charge_assign,power,ePrice,resultsS3E2,resultsS3E8,resultsS5E2,resultsS5E8,deployS3E2
11,11,11,11,30000473,20000,"[800, 825, 1000, 1100, 1115, 1230, 1640, 1910]","[815, 835, 1033, 1105, 1120, 1240, 1715, 1924]","[15, 10, 33, 5, 5, 10, 35, 14]","[6.593, 1.112, 5.254, 0.159, 1.125, 8.479, 18....","[10.0, 85.0, 27.0, 10.0, 70.0, 240.0, 115.0, 2...",2,"['Public', 'Public', 'Public', 'Public', 'Home...","['Home', 'Public', 'Public', 'Public', 'Public...","['""\'Home\'""', ' "" \'Public\'""', ' "" \'Public\...",0,1,9,0,30797,176842,0,0.093100,0.010122,1,0,"[6.0, 50.0, 50.0, 50.0, 50.0, 6.0, 50.0, 50.0,...","[0.159, 0.35, 0.35, 0.35, 0.35, 0.159, 0.35, 0...","[1.0, 0.16666666666666666, 0.0, 0.047626262626...","[1.0, 0.16666666666666666, 0.04762626262626265...","[1.0, 0.14195757575757578, 0.0, 0.0, 0.0, 0.0,...","[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4407393939393...",1.0
12,12,12,12,30000482,30000,"[945, 1205, 1332]","[1000, 1220, 1350]","[15, 15, 18]","[7.594, 3.109, 10.97]","[125.0, 72.0, 630.0]",9,"['Public', 'Public', 'Home']","['Home', 'Public', 'Public', 'Home']","['""\'Home\'""', ' "" \'Public\'""', ' "" \'Public\...",0,0,4,0,36996,187706,0,0.330093,0.035370,0,0,"[6.0, 50.0, 50.0, 6.0]","[0.118, 0.35, 0.35, 0.118]","[1.0, 0.07074545454545456, 0.0, 0.0]","[1.0, 0.4343818181818182, 0.0, 0.0]","[-0.0, 0.0, 0.0, 0.0]","[1.0, 0.313169696969697, 0.0, 0.0]",1.0
16,16,16,16,30000611,20000,"[1430, 1630]","[1433, 1635]","[3, 5]","[1.237, 1.237]","[117.0, 115.0]",5,"['Public', 'Home']","['Home', 'Public', 'Home']","['""\'Home\'""', ' "" \'Public\'""', ' "" \'Home\'""']",0,1,3,0,21583,102365,0,0.070090,0.013416,0,0,"[6.0, 50.0, 6.0]","[0.118, 0.35, 0.118]","[-0.0, 0.0, 0.0]","[1.0, 0.31802424242424243, 0.0]","[-0.0, 0.0, 0.0]","[1.0, 0.19681212121212124, 0.0]",-0.0
24,24,24,24,30000885,30000,"[945, 1235]","[1110, 1330]","[85, 55]","[37.609, 37.97]","[85.0, 642.0]",5,"['Public', 'Home']","['Home', 'Public', 'Home']","['""\'Home\'""', ' "" \'Public\'""', ' "" \'Home\'""']",0,1,3,0,21583,102365,1,0.070090,0.013416,0,0,"[6.0, 50.0, 6.0]","[0.118, 0.35, 0.118]","[1.0, 0.3974484848484849, 0.0]","[1.0, 0.6521757575757576, 0.10890909090909096]","[1.0, 0.27623636363636367, 0.0]","[1.0, 0.5309636363636364, 0.10890909090909096]",1.0
27,27,27,27,30001039,30000,"[1215, 1320, 1615]","[1230, 1345, 1645]","[15, 25, 30]","[1.321, 3.44, 5.263]","[50.0, 150.0, 453.0]",2,"['Public', 'Public', 'Home']","['Home', 'Public', 'Public', 'Home']","['""\'Home\'""', ' "" \'Public\'""', ' "" \'Public\...",1,1,4,0,30797,176842,0,0.093100,0.010122,0,0,"[6.0, 50.0, 50.0, 6.0]","[0.159, 0.35, 0.35, 0.159]","[1.0, 0.00014545454545455096, 0.0, 0.0]","[1.0, 0.3637818181818182, 0.0, 0.0]","[-0.0, 0.0, 0.0, 0.0]","[1.0, 0.24256969696969696, 0.0, 0.0]",1.0

In [20]:
sharelistS3E2_C1 = []
for i in range(9):
    temp = np.mean(cluster0S3E2[cluster0S3E2['CENSUS_D'] == i+1]['deployS3E2'])
    sharelistS3E2_C1.append(temp)

In [21]:
cluster0S3E8 = cluster0[cluster0['resultsS3E8']!='infeasible']
cluster0S3E8.loc[:,'resultsS3E8'] = cluster0S3E8.loc[:,'resultsS3E8'].apply(lambda x: literal_eval(x))
cluster0S3E8['deployS3E8']=cluster0S3E8['resultsS3E8'].agg(deploy_or_not)
# cluster0S3E2.head()
sharelistS3E8_C1 = []
for i in range(9):
    temp = np.mean(cluster0S3E8[cluster0S3E8['CENSUS_D'] == i+1]['deployS3E8'])
    sharelistS3E8_C1.append(temp)
    
sharelistS3E8_C1

/Users/cheng_xi/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
/Users/cheng_xi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

[0.9047619047619048,
 0.8776824034334764,
 0.8626817447495961,
 0.8563218390804598,
 0.8682487725040916,
 0.8723404255319149,
 0.8264058679706602,
 0.8760330578512396,
 0.8576186511240633]

In [22]:
cluster0S5E2 = cluster0[cluster0['resultsS5E2']!='infeasible']
cluster0S5E2.loc[:,'resultsS5E2'] = cluster0S5E2.loc[:,'resultsS5E2'].apply(lambda x: literal_eval(x))
cluster0S5E2['deployS5E2']=cluster0S5E2['resultsS5E2'].agg(deploy_or_not)
# cluster0S3E2.head()
sharelistS5E2_C1 = []
for i in range(9):
    temp = np.mean(cluster0S5E2[cluster0S5E2['CENSUS_D'] == i+1]['deployS5E2'])
    sharelistS5E2_C1.append(temp)
    
sharelistS5E2_C1

/Users/cheng_xi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

[0.22988505747126436,
 0.19393939393939394,
 0.19909502262443438,
 0.11290322580645161,
 0.22213855421686746,
 0.3333333333333333,
 0.20555555555555555,
 0.2109375,
 0.15602836879432624]

In [23]:
cluster0S5E8 = cluster0[cluster0['resultsS5E8']!='infeasible']
cluster0S5E8.loc[:,'resultsS5E8'] = cluster0S5E8.loc[:,'resultsS5E8'].apply(lambda x: literal_eval(x))
cluster0S5E8['deployS5E8']=cluster0S5E8['resultsS5E8'].agg(deploy_or_not)
# cluster0S3E2.head()
sharelistS5E8_C1 = []
for i in range(9):
    temp = np.mean(cluster0S5E8[cluster0S5E8['CENSUS_D'] == i+1]['deployS5E8'])
    sharelistS5E8_C1.append(temp)
    
sharelistS5E8_C1

/Users/cheng_xi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

[0.8837209302325582,
 0.8561224489795919,
 0.8381240544629349,
 0.8315217391304348,
 0.8205904617713853,
 0.8431372549019608,
 0.7774049217002237,
 0.8700787401574803,
 0.8212867355043686]

In [ ]:
cluster1S3E2['resultsS3E2'].agg(deploy_or_not)

In [ ]:
cluster1S3E2_copy.head()

In [ ]:
cluster1S3E2_copy.head()

In [ ]:
type(cluster1S3E2_copy.loc[0,'resultsS3E2'])  == list

In [ ]:
# cluster1S3E2_copy.loc[2,'resultsS3E2'][0]
cluster1S3E2_copy = cluster1S3E2.reset_index()
for i in range(len(cluster1S3E2)):
    if type(cluster1S3E2_copy.loc[i,'resultsS3E2']) == list:
        cluster1S3E2_copy.loc[i,'deployS3E2']=cluster1S3E2_copy.loc[i,'resultsS3E2'][0]
    else:
        cluster1S3E2_copy.loc[i,'deployS3E2']=literal_eval(cluster1S3E2_copy.loc[i,'resultsS3E2'])[0]

In [25]:
cluster1S3E2 = cluster1[cluster1['resultsS3E2']!='infeasible']
cluster1S3E2_copy = cluster1S3E2.reset_index()
for i in range(len(cluster1S3E2)):
    if type(cluster1S3E2_copy.loc[i,'resultsS3E2']) == list:
        cluster1S3E2_copy.loc[i,'deployS3E2']=cluster1S3E2_copy.loc[i,'resultsS3E2'][0]
    else:
        cluster1S3E2_copy.loc[i,'deployS3E2']=literal_eval(cluster1S3E2_copy.loc[i,'resultsS3E2'])[0]
sharelistS3E2_C2 = []
for i in range(9):
    temp = np.mean(cluster1S3E2_copy[cluster1S3E2_copy['CENSUS_D'] == i+1]['deployS3E2'])
    sharelistS3E2_C2.append(temp)

    
cluster1S3E8 = cluster1[cluster1['resultsS3E8']!='infeasible']
cluster1S3E8_copy = cluster1S3E8.reset_index()
for i in range(len(cluster1S3E8)):
    if type(cluster1S3E8_copy.loc[i,'resultsS3E8']) == list:
        cluster1S3E8_copy.loc[i,'deployS3E8']=cluster1S3E8_copy.loc[i,'resultsS3E8'][0]
    else:
        cluster1S3E8_copy.loc[i,'deployS3E8']=literal_eval(cluster1S3E8_copy.loc[i,'resultsS3E8'])[0]
sharelistS3E8_C2 = []
for i in range(9):
    temp = np.mean(cluster1S3E8_copy[cluster1S3E8_copy['CENSUS_D'] == i+1]['deployS3E8'])
    sharelistS3E8_C2.append(temp)


cluster1S5E2 = cluster1[cluster1['resultsS5E2']!='infeasible']
cluster1S5E2_copy = cluster1S5E2.reset_index()
for i in range(len(cluster1S5E2)):
    if type(cluster1S5E2_copy.loc[i,'resultsS5E2']) == list:
        cluster1S5E2_copy.loc[i,'deployS5E2']=cluster1S5E2_copy.loc[i,'resultsS5E2'][0]
    else:
        cluster1S5E2_copy.loc[i,'deployS5E2']=literal_eval(cluster1S5E2_copy.loc[i,'resultsS5E2'])[0]
sharelistS5E2_C2 = []
for i in range(9):
    temp = np.mean(cluster1S5E2_copy[cluster1S5E2_copy['CENSUS_D'] == i+1]['deployS5E2'])
    sharelistS5E2_C2.append(temp)
    
    
cluster1S5E8 = cluster1[cluster1['resultsS5E8']!='infeasible']
cluster1S5E8_copy = cluster1S5E8.reset_index()
for i in range(len(cluster1S5E8)):
    if type(cluster1S5E8_copy.loc[i,'resultsS5E8']) == list:
        cluster1S5E8_copy.loc[i,'deployS5E8']=cluster1S5E8_copy.loc[i,'resultsS5E8'][0]
    else:
        cluster1S5E8_copy.loc[i,'deployS5E8']=literal_eval(cluster1S5E8_copy.loc[i,'resultsS5E8'])[0]
sharelistS5E8_C2 = []
for i in range(9):
    temp = np.mean(cluster1S5E8_copy[cluster1S5E8_copy['CENSUS_D'] == i+1]['deployS5E8'])
    sharelistS5E8_C2.append(temp)

In [26]:
cluster2S3E2 = cluster2[cluster2['resultsS3E2']!='infeasible']
cluster2S3E2_copy = cluster2S3E2.reset_index()
for i in range(len(cluster2S3E2)):
    if type(cluster2S3E2_copy.loc[i,'resultsS3E2']) == list:
        cluster2S3E2_copy.loc[i,'deployS3E2']=cluster2S3E2_copy.loc[i,'resultsS3E2'][0]
    else:
        cluster2S3E2_copy.loc[i,'deployS3E2']=literal_eval(cluster2S3E2_copy.loc[i,'resultsS3E2'])[0]
sharelistS3E2_C3 = []
for i in range(9):
    temp = np.mean(cluster2S3E2_copy[cluster2S3E2_copy['CENSUS_D'] == i+1]['deployS3E2'])
    sharelistS3E2_C3.append(temp)

    
cluster2S3E8 = cluster2[cluster2['resultsS3E8']!='infeasible']
cluster2S3E8_copy = cluster2S3E8.reset_index()
for i in range(len(cluster2S3E8)):
    if type(cluster2S3E8_copy.loc[i,'resultsS3E8']) == list:
        cluster2S3E8_copy.loc[i,'deployS3E8']=cluster2S3E8_copy.loc[i,'resultsS3E8'][0]
    else:
        cluster2S3E8_copy.loc[i,'deployS3E8']=literal_eval(cluster2S3E8_copy.loc[i,'resultsS3E8'])[0]
sharelistS3E8_C3 = []
for i in range(9):
    temp = np.mean(cluster2S3E8_copy[cluster2S3E8_copy['CENSUS_D'] == i+1]['deployS3E8'])
    sharelistS3E8_C3.append(temp)


cluster2S5E2 = cluster2[cluster2['resultsS5E2']!='infeasible']
cluster2S5E2_copy = cluster2S5E2.reset_index()
for i in range(len(cluster2S5E2)):
    if type(cluster2S5E2_copy.loc[i,'resultsS5E2']) == list:
        cluster2S5E2_copy.loc[i,'deployS5E2']=cluster2S5E2_copy.loc[i,'resultsS5E2'][0]
    else:
        cluster2S5E2_copy.loc[i,'deployS5E2']=literal_eval(cluster2S5E2_copy.loc[i,'resultsS5E2'])[0]
sharelistS5E2_C3 = []
for i in range(9):
    temp = np.mean(cluster2S5E2_copy[cluster2S5E2_copy['CENSUS_D'] == i+1]['deployS5E2'])
    sharelistS5E2_C3.append(temp)
    
    
cluster2S5E8 = cluster2[cluster2['resultsS5E8']!='infeasible']
cluster2S5E8_copy = cluster2S5E8.reset_index()
for i in range(len(cluster2S5E8)):
    if type(cluster2S5E8_copy.loc[i,'resultsS5E8']) == list:
        cluster2S5E8_copy.loc[i,'deployS5E8']=cluster2S5E8_copy.loc[i,'resultsS5E8'][0]
    else:
        cluster2S5E8_copy.loc[i,'deployS5E8']=literal_eval(cluster2S5E8_copy.loc[i,'resultsS5E8'])[0]
sharelistS5E8_C3 = []
for i in range(9):
    temp = np.mean(cluster2S5E8_copy[cluster2S5E8_copy['CENSUS_D'] == i+1]['deployS5E8'])
    sharelistS5E8_C3.append(temp)

In [28]:
MudShare = pd.DataFrame()
  
# print(MudShare)
  
# append columns to an empty DataFrame
MudShare['Census Division'] = ['New England', 'Middle Atlantic', 'East North Central',
                               'West North Central', 'South Atlantic', 'East South Central',
                               'West South Central', 'Mountain', 'Pacific']

MudShare['Cluster 1 (I30E20)'] = sharelistS3E2_C1
MudShare['Cluster 2 (I30E20)'] = sharelistS3E2_C2
MudShare['Cluster 3 (I30E20)'] = sharelistS3E2_C3

MudShare['Cluster 1 (I30E80)'] = sharelistS3E8_C1
MudShare['Cluster 2 (I30E80)'] = sharelistS3E8_C2
MudShare['Cluster 3 (I30E80)'] = sharelistS3E8_C3

MudShare['Cluster 1 (I50E20)'] = sharelistS5E2_C1
MudShare['Cluster 2 (I50E20)'] = sharelistS5E2_C2
MudShare['Cluster 3 (I50E20)'] = sharelistS5E2_C3

MudShare['Cluster 1 (I50E80)'] = sharelistS5E8_C1
MudShare['Cluster 2 (I50E80)'] = sharelistS5E8_C2
MudShare['Cluster 3 (I50E80)'] = sharelistS5E8_C3

In [29]:
MudShare

,Census Division,Cluster 1 (I30E20),Cluster 2 (I30E20),Cluster 3 (I30E20),Cluster 1 (I30E80),Cluster 2 (I30E80),Cluster 3 (I30E80),Cluster 1 (I50E20),Cluster 2 (I50E20),Cluster 3 (I50E20),Cluster 1 (I50E80),Cluster 2 (I50E80),Cluster 3 (I50E80)
0,New England,0.529412,0.333333,0.512987,0.904762,1.000000,0.744186,0.229885,0.181818,0.273504,0.883721,0.909091,0.701449
1,Middle Atlantic,0.541226,0.557522,0.530709,0.877682,0.891892,0.734160,0.193939,0.285714,0.260476,0.856122,0.871795,0.673820
2,East North Central,0.488746,0.519481,0.492832,0.862682,0.973684,0.680800,0.199095,0.226190,0.246178,0.838124,0.940476,0.630933
3,West North Central,0.488636,0.444444,0.446352,0.856322,0.925926,0.702407,0.112903,0.148148,0.159844,0.831522,0.888889,0.644841
4,South Atlantic,0.590615,0.704082,0.541212,0.868249,0.964286,0.713249,0.222139,0.311628,0.241817,0.820590,0.939535,0.639444
5,East South Central,0.617021,0.600000,0.611111,0.872340,1.000000,0.788889,0.333333,0.200000,0.267327,0.843137,1.000000,0.712871
6,West South Central,0.506053,0.578125,0.504868,0.826406,0.912698,0.683789,0.205556,0.224638,0.240537,0.777405,0.897810,0.611799
7,Mountain,0.540984,0.441176,0.470135,0.876033,0.941176,0.694716,0.210938,0.257143,0.197232,0.870079,0.914286,0.631858
8,Pacific,0.454996,0.546961,0.496334,0.857619,0.933702,0.713771,0.156028,0.203980,0.230875,0.821287,0.885572,0.662106

In [30]:
MudShare.to_excel("ShareEnergySummaryDiffLevel_LEVEL2.xlsx",
...              sheet_name='MUDShare_Cluster')

In [ ]:
df.head()

In [31]:
income0 = df[df['income_classes'] == 0]
income1 = df[df['income_classes'] == 1]
income2 = df[df['income_classes'] == 2]

In [32]:
income0S3E2 = income0[income0['resultsS3E2']!='infeasible']
income0S3E2_copy = income0S3E2.reset_index()
for i in range(len(income0S3E2)):
    if type(income0S3E2_copy.loc[i,'resultsS3E2']) == list:
        income0S3E2_copy.loc[i,'deployS3E2']=income0S3E2_copy.loc[i,'resultsS3E2'][0]
    else:
        income0S3E2_copy.loc[i,'deployS3E2']=literal_eval(income0S3E2_copy.loc[i,'resultsS3E2'])[0]
sharelistS3E2_I0 = []
for i in range(9):
    temp = np.mean(income0S3E2_copy[income0S3E2_copy['CENSUS_D'] == i+1]['deployS3E2'])
    sharelistS3E2_I0.append(temp)

    
income0S3E8 = income0[income0['resultsS3E8']!='infeasible']
income0S3E8_copy = income0S3E8.reset_index()
for i in range(len(income0S3E8)):
    if type(income0S3E8_copy.loc[i,'resultsS3E8']) == list:
        income0S3E8_copy.loc[i,'deployS3E8']=income0S3E8_copy.loc[i,'resultsS3E8'][0]
    else:
        income0S3E8_copy.loc[i,'deployS3E8']=literal_eval(income0S3E8_copy.loc[i,'resultsS3E8'])[0]
sharelistS3E8_I0 = []
for i in range(9):
    temp = np.mean(income0S3E8_copy[income0S3E8_copy['CENSUS_D'] == i+1]['deployS3E8'])
    sharelistS3E8_I0.append(temp)


income0S5E2 = income0[income0['resultsS5E2']!='infeasible']
income0S5E2_copy = income0S5E2.reset_index()
for i in range(len(income0S5E2)):
    if type(income0S5E2_copy.loc[i,'resultsS5E2']) == list:
        income0S5E2_copy.loc[i,'deployS5E2']=income0S5E2_copy.loc[i,'resultsS5E2'][0]
    else:
        income0S5E2_copy.loc[i,'deployS5E2']=literal_eval(income0S5E2_copy.loc[i,'resultsS5E2'])[0]
sharelistS5E2_I0 = []
for i in range(9):
    temp = np.mean(income0S5E2_copy[income0S5E2_copy['CENSUS_D'] == i+1]['deployS5E2'])
    sharelistS5E2_I0.append(temp)
    
    
income0S5E8 = income0[income0['resultsS5E8']!='infeasible']
income0S5E8_copy = income0S5E8.reset_index()
for i in range(len(income0S5E8)):
    if type(income0S5E8_copy.loc[i,'resultsS5E8']) == list:
        income0S5E8_copy.loc[i,'deployS5E8']=income0S5E8_copy.loc[i,'resultsS5E8'][0]
    else:
        income0S5E8_copy.loc[i,'deployS5E8']=literal_eval(income0S5E8_copy.loc[i,'resultsS5E8'])[0]
sharelistS5E8_I0 = []
for i in range(9):
    temp = np.mean(income0S5E8_copy[income0S5E8_copy['CENSUS_D'] == i+1]['deployS5E8'])
    sharelistS5E8_I0.append(temp)

In [33]:
income1S3E2 = income1[income1['resultsS3E2']!='infeasible']
income1S3E2_copy = income1S3E2.reset_index()
for i in range(len(income1S3E2)):
    if type(income1S3E2_copy.loc[i,'resultsS3E2']) == list:
        income1S3E2_copy.loc[i,'deployS3E2']=income1S3E2_copy.loc[i,'resultsS3E2'][0]
    else:
        income1S3E2_copy.loc[i,'deployS3E2']=literal_eval(income1S3E2_copy.loc[i,'resultsS3E2'])[0]
sharelistS3E2_I1 = []
for i in range(9):
    temp = np.mean(income1S3E2_copy[income1S3E2_copy['CENSUS_D'] == i+1]['deployS3E2'])
    sharelistS3E2_I1.append(temp)

    
income1S3E8 = income1[income1['resultsS3E8']!='infeasible']
income1S3E8_copy = income1S3E8.reset_index()
for i in range(len(income1S3E8)):
    if type(income1S3E8_copy.loc[i,'resultsS3E8']) == list:
        income1S3E8_copy.loc[i,'deployS3E8']=income1S3E8_copy.loc[i,'resultsS3E8'][0]
    else:
        income1S3E8_copy.loc[i,'deployS3E8']=literal_eval(income1S3E8_copy.loc[i,'resultsS3E8'])[0]
sharelistS3E8_I1 = []
for i in range(9):
    temp = np.mean(income1S3E8_copy[income1S3E8_copy['CENSUS_D'] == i+1]['deployS3E8'])
    sharelistS3E8_I1.append(temp)


income1S5E2 = income1[income1['resultsS5E2']!='infeasible']
income1S5E2_copy = income1S5E2.reset_index()
for i in range(len(income1S5E2)):
    if type(income1S5E2_copy.loc[i,'resultsS5E2']) == list:
        income1S5E2_copy.loc[i,'deployS5E2']=income1S5E2_copy.loc[i,'resultsS5E2'][0]
    else:
        income1S5E2_copy.loc[i,'deployS5E2']=literal_eval(income1S5E2_copy.loc[i,'resultsS5E2'])[0]
sharelistS5E2_I1 = []
for i in range(9):
    temp = np.mean(income1S5E2_copy[income1S5E2_copy['CENSUS_D'] == i+1]['deployS5E2'])
    sharelistS5E2_I1.append(temp)
    
    
income1S5E8 = income1[income1['resultsS5E8']!='infeasible']
income1S5E8_copy = income1S5E8.reset_index()
for i in range(len(income1S5E8)):
    if type(income1S5E8_copy.loc[i,'resultsS5E8']) == list:
        income1S5E8_copy.loc[i,'deployS5E8']=income1S5E8_copy.loc[i,'resultsS5E8'][0]
    else:
        income1S5E8_copy.loc[i,'deployS5E8']=literal_eval(income1S5E8_copy.loc[i,'resultsS5E8'])[0]
sharelistS5E8_I1 = []
for i in range(9):
    temp = np.mean(income1S5E8_copy[income1S5E8_copy['CENSUS_D'] == i+1]['deployS5E8'])
    sharelistS5E8_I1.append(temp)

In [34]:
income2S3E2 = income2[income2['resultsS3E2']!='infeasible']
income2S3E2_copy = income2S3E2.reset_index()
for i in range(len(income2S3E2)):
    if type(income2S3E2_copy.loc[i,'resultsS3E2']) == list:
        income2S3E2_copy.loc[i,'deployS3E2']=income2S3E2_copy.loc[i,'resultsS3E2'][0]
    else:
        income2S3E2_copy.loc[i,'deployS3E2']=literal_eval(income2S3E2_copy.loc[i,'resultsS3E2'])[0]
sharelistS3E2_I2 = []
for i in range(9):
    temp = np.mean(income2S3E2_copy[income2S3E2_copy['CENSUS_D'] == i+1]['deployS3E2'])
    sharelistS3E2_I2.append(temp)

    
income2S3E8 = income2[income2['resultsS3E8']!='infeasible']
income2S3E8_copy = income2S3E8.reset_index()
for i in range(len(income2S3E8)):
    if type(income2S3E8_copy.loc[i,'resultsS3E8']) == list:
        income2S3E8_copy.loc[i,'deployS3E8']=income2S3E8_copy.loc[i,'resultsS3E8'][0]
    else:
        income2S3E8_copy.loc[i,'deployS3E8']=literal_eval(income2S3E8_copy.loc[i,'resultsS3E8'])[0]
sharelistS3E8_I2 = []
for i in range(9):
    temp = np.mean(income2S3E8_copy[income2S3E8_copy['CENSUS_D'] == i+1]['deployS3E8'])
    sharelistS3E8_I2.append(temp)


income2S5E2 = income2[income2['resultsS5E2']!='infeasible']
income2S5E2_copy = income2S5E2.reset_index()
for i in range(len(income2S5E2)):
    if type(income2S5E2_copy.loc[i,'resultsS5E2']) == list:
        income2S5E2_copy.loc[i,'deployS5E2']=income2S5E2_copy.loc[i,'resultsS5E2'][0]
    else:
        income2S5E2_copy.loc[i,'deployS5E2']=literal_eval(income2S5E2_copy.loc[i,'resultsS5E2'])[0]
sharelistS5E2_I2 = []
for i in range(9):
    temp = np.mean(income2S5E2_copy[income2S5E2_copy['CENSUS_D'] == i+1]['deployS5E2'])
    sharelistS5E2_I2.append(temp)
    
    
income2S5E8 = income2[income2['resultsS5E8']!='infeasible']
income2S5E8_copy = income2S5E8.reset_index()
for i in range(len(income2S5E8)):
    if type(income2S5E8_copy.loc[i,'resultsS5E8']) == list:
        income2S5E8_copy.loc[i,'deployS5E8']=income2S5E8_copy.loc[i,'resultsS5E8'][0]
    else:
        income2S5E8_copy.loc[i,'deployS5E8']=literal_eval(income2S5E8_copy.loc[i,'resultsS5E8'])[0]
sharelistS5E8_I2 = []
for i in range(9):
    temp = np.mean(income2S5E8_copy[income2S5E8_copy['CENSUS_D'] == i+1]['deployS5E8'])
    sharelistS5E8_I2.append(temp)

In [35]:
MudShareIncome = pd.DataFrame()
  
# print(MudShare)
  
# append columns to an empty DataFrame
MudShareIncome['Census Division'] = ['New England', 'Middle Atlantic', 'East North Central',
                               'West North Central', 'South Atlantic', 'East South Central',
                               'West South Central', 'Mountain', 'Pacific']

MudShareIncome['Income 1 (I30E20)'] = sharelistS3E2_I0
MudShareIncome['Income 2 (I30E20)'] = sharelistS3E2_I1
MudShareIncome['Income 3 (I30E20)'] = sharelistS3E2_I2

MudShareIncome['Income 1 (I30E80)'] = sharelistS3E8_I0
MudShareIncome['Income 2 (I30E80)'] = sharelistS3E8_I1
MudShareIncome['Income 3 (I30E80)'] = sharelistS3E8_I2

MudShareIncome['Income 1 (I50E20)'] = sharelistS5E2_I0
MudShareIncome['Income 2 (I50E20)'] = sharelistS5E2_I1
MudShareIncome['Income 3 (I50E20)'] = sharelistS5E2_I2

MudShareIncome['Income 1 (I50E80)'] = sharelistS5E8_I0
MudShareIncome['Income 2 (I50E80)'] = sharelistS5E8_I1
MudShareIncome['Income 3 (I50E80)'] = sharelistS5E8_I2

In [ ]:
import xlsxwriter
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('ShareEnergySummaryDiffLevel.xlsx', engine='xlsxwriter')

# Write each dataframe to a different worksheet.
MudShare.to_excel(writer, sheet_name='MUDShare_Cluster')
MudShareIncome.to_excel(writer, sheet_name='MUDShare_Income')
# df3.to_excel(writer, sheet_name='Sheet3')

In [36]:
MudShare.to_excel("ShareCluster_MUDLEVEL2.xlsx",
...              sheet_name='MUDShare_Cluster')  
MudShareIncome.to_excel("ShareIncome_MUDLEVEL2.xlsx",
...              sheet_name='MUDShare_Income')

energy use

In [ ]:
df.loc[:,'WHYFROM_GENERAL'] = df.loc[:,'WHYFROM_GENERAL'].apply(lambda x: literal_eval(x))
df.loc[0,'WHYFROM_GENERAL'][0]

In [ ]:
energy = 0
for i in range(len(df.loc[0,'resultsS3E8'])-1):
    if df.loc[0,'WHYFROM_GENERAL'][i] == 'Home':
        energy = energy+P[0]*df.loc[0,'resultsS3E8'][i+1]
    elif df.loc[0,'WHYFROM_GENERAL'][i] == 'Work':
        energy = energy+P[1]*df.loc[0,'resultsS3E8'][i+1]
    elif df.loc[0,'WHYFROM_GENERAL'][i] == 'Public':
        energy = energy+P[2]*df.loc[0,'resultsS3E8'][i+1]
        
energy

In [ ]:
#energy power:
P = [1, 0, 0]

In [ ]:
def energy_compute(x1,x2):
    energy = 0
    if x1 == 'infeasible':
        return 'infeasible'
    else:
        for i in range(len(x1)-1):
            if x2[i] == 'Home':
                energy = energy+P[0]*x1[i+1]
            elif x2[i] == 'Work':
                energy = energy+P[1]*x1[i+1]
            elif x2[i] == 'Public':
                energy = energy+P[2]*x1[i+1]

    return energy

In [ ]:
sample = df.head(10)

In [ ]:
type(sample.loc[0,'resultsS3E8'][0])

In [ ]:
sample.loc[0,'resultsS3E8']

In [ ]:
sample

In [ ]:
len(literal_eval(sample.loc[5,'resultsS3E8']))

In [ ]:
i
len(sample.loc[5,'resultsS3E8'])

In [ ]:
energyList

In [ ]:
0.43591515151515153 + 50*0.0295454+7.724940478959219e-18*50

In [ ]:
sample.loc[1,'resultsS3E8']

In [ ]:
sample.loc[1,'WHYFROM_GENERAL']

In [ ]:
P

In [ ]:
energyListS3E2 = []
for i in range(len(df)): 
    if df.loc[i,'resultsS3E2'] == 'infeasible':
        energy = 'infeasible'
    else:
        energy = 0
        if type(df.loc[i,'resultsS3E2']) == list:
            for j in range(len(df.loc[i,'resultsS3E2'])-1):
                if df.loc[i,'WHYFROM_GENERAL'][j] == 'Home':
                    energy = energy + P[0]*df.loc[i,'resultsS3E2'][j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Work':
                    energy = energy + P[1]*df.loc[i,'resultsS3E2'][j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Public':
                    energy = energy + P[2]*df.loc[i,'resultsS3E2'][j+1]
        else:
            for j in range(len(literal_eval(df.loc[i,'resultsS3E2']))-1):
                if df.loc[i,'WHYFROM_GENERAL'][j] == 'Home':
                    energy = energy + P[0]*literal_eval(df.loc[i,'resultsS3E2'])[j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Work':
                    energy = energy + P[1]*literal_eval(df.loc[i,'resultsS3E2'])[j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Public':
                    energy = energy + P[2]*literal_eval(df.loc[i,'resultsS3E2'])[j+1]
        
                    
    energyListS3E2.append(energy)

In [ ]:
# df['energyS3E2'] = energyListS3E2
df.head()

In [ ]:
energyListS3E8 = []
for i in range(len(df)): 
    if df.loc[i,'resultsS3E8'] == 'infeasible':
        energy = 'infeasible'
    else:
        energy = 0
        if type(df.loc[i,'resultsS3E8']) == list:
            for j in range(len(df.loc[i,'resultsS3E8'])-1):
                if df.loc[i,'WHYFROM_GENERAL'][j] == 'Home':
                    energy = energy + P[0]*df.loc[i,'resultsS3E8'][j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Work':
                    energy = energy + P[1]*df.loc[i,'resultsS3E8'][j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Public':
                    energy = energy + P[2]*df.loc[i,'resultsS3E8'][j+1]
        else:
            for j in range(len(literal_eval(df.loc[i,'resultsS3E8']))-1):
                if df.loc[i,'WHYFROM_GENERAL'][j] == 'Home':
                    energy = energy + P[0]*literal_eval(df.loc[i,'resultsS3E8'])[j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Work':
                    energy = energy + P[1]*literal_eval(df.loc[i,'resultsS3E8'])[j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Public':
                    energy = energy + P[2]*literal_eval(df.loc[i,'resultsS3E8'])[j+1]
        
                    
    energyListS3E8.append(energy)

In [ ]:
energyListS5E2 = []
for i in range(len(df)): 
    if df.loc[i,'resultsS5E2'] == 'infeasible':
        energy = 'infeasible'
    else:
        energy = 0
        if type(df.loc[i,'resultsS5E2']) == list:
            for j in range(len(df.loc[i,'resultsS5E2'])-1):
                if df.loc[i,'WHYFROM_GENERAL'][j] == 'Home':
                    energy = energy + P[0]*df.loc[i,'resultsS5E2'][j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Work':
                    energy = energy + P[1]*df.loc[i,'resultsS5E2'][j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Public':
                    energy = energy + P[2]*df.loc[i,'resultsS5E2'][j+1]
        else:
            for j in range(len(literal_eval(df.loc[i,'resultsS5E2']))-1):
                if df.loc[i,'WHYFROM_GENERAL'][j] == 'Home':
                    energy = energy + P[0]*literal_eval(df.loc[i,'resultsS5E2'])[j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Work':
                    energy = energy + P[1]*literal_eval(df.loc[i,'resultsS5E2'])[j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Public':
                    energy = energy + P[2]*literal_eval(df.loc[i,'resultsS5E2'])[j+1]
        
                    
    energyListS5E2.append(energy)

In [ ]:
energyListS5E8 = []
for i in range(len(df)): 
    if df.loc[i,'resultsS5E8'] == 'infeasible':
        energy = 'infeasible'
    else:
        energy = 0
        if type(df.loc[i,'resultsS5E8']) == list:
            for j in range(len(df.loc[i,'resultsS5E8'])-1):
                if df.loc[i,'WHYFROM_GENERAL'][j] == 'Home':
                    energy = energy + P[0]*df.loc[i,'resultsS5E8'][j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Work':
                    energy = energy + P[1]*df.loc[i,'resultsS5E8'][j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Public':
                    energy = energy + P[2]*df.loc[i,'resultsS5E8'][j+1]
        else:
            for j in range(len(literal_eval(df.loc[i,'resultsS5E8']))-1):
                if df.loc[i,'WHYFROM_GENERAL'][j] == 'Home':
                    energy = energy + P[0]*literal_eval(df.loc[i,'resultsS5E8'])[j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Work':
                    energy = energy + P[1]*literal_eval(df.loc[i,'resultsS5E8'])[j+1]
                elif df.loc[i,'WHYFROM_GENERAL'][j] == 'Public':
                    energy = energy + P[2]*literal_eval(df.loc[i,'resultsS5E8'])[j+1]
        
                    
    energyListS5E8.append(energy)

In [ ]:
sample['EnergyS3E2']=sample.apply(lambda x: energy_compute(x['resultsS3E2'],x['WHYFROM_GENERAL']), axis=1)

In [ ]:
df['energyS3E2'] = energyListS3E2
df['energyS3E8'] = energyListS3E8
df['energyS5E2'] = energyListS5E2
df['energyS5E8'] = energyListS5E8
df.head()

In [ ]:
eincome0 = df[df['income_classes'] == 0]
eincome1 = df[df['income_classes'] == 1]
eincome2 = df[df['income_classes'] == 2]

In [ ]:
eincome0S3E2 = eincome0[eincome0['resultsS3E2']!='infeasible']
eincome0S3E2.shape

In [ ]:
np.mean(eincome0S3E2[eincome0S3E2['CENSUS_D'] == 9]['energyS3E2'])

In [ ]:
eincome0S3E2 = eincome0[eincome0['resultsS3E2']!='infeasible']
energylistS3E2_I0 = []
for i in range(9):
    temp = np.mean(eincome0S3E2[eincome0S3E2['CENSUS_D'] == i+1]['energyS3E2'])
    energylistS3E2_I0.append(temp)
    
eincome0S3E8 = eincome0[eincome0['resultsS3E8']!='infeasible']
energylistS3E8_I0 = []
for i in range(9):
    temp = np.mean(eincome0S3E8[eincome0S3E8['CENSUS_D'] == i+1]['energyS3E8'])
    energylistS3E8_I0.append(temp)

eincome0S5E2 = eincome0[eincome0['resultsS5E2']!='infeasible']
energylistS5E2_I0 = []
for i in range(9):
    temp = np.mean(eincome0S5E2[eincome0S5E2['CENSUS_D'] == i+1]['energyS5E2'])
    energylistS5E2_I0.append(temp)
     
eincome0S5E8 = eincome0[eincome0['resultsS5E8']!='infeasible']
energylistS5E8_I0 = []
for i in range(9):
    temp = np.mean(eincome0S5E8[eincome0S5E8['CENSUS_D'] == i+1]['energyS5E8'])
    energylistS5E8_I0.append(temp)

In [ ]:
eincome1S3E2 = eincome1[eincome1['resultsS3E2']!='infeasible']
energylistS3E2_I1 = []
for i in range(9):
    temp = np.mean(eincome1S3E2[eincome1S3E2['CENSUS_D'] == i+1]['energyS3E2'])
    energylistS3E2_I1.append(temp)
    
eincome1S3E8 = eincome1[eincome1['resultsS3E8']!='infeasible']
energylistS3E8_I1 = []
for i in range(9):
    temp = np.mean(eincome1S3E8[eincome1S3E8['CENSUS_D'] == i+1]['energyS3E8'])
    energylistS3E8_I1.append(temp)

eincome1S5E2 = eincome1[eincome1['resultsS5E2']!='infeasible']
energylistS5E2_I1 = []
for i in range(9):
    temp = np.mean(eincome1S5E2[eincome1S5E2['CENSUS_D'] == i+1]['energyS5E2'])
    energylistS5E2_I1.append(temp)
     
eincome1S5E8 = eincome1[eincome1['resultsS5E8']!='infeasible']
energylistS5E8_I1 = []
for i in range(9):
    temp = np.mean(eincome1S5E8[eincome1S5E8['CENSUS_D'] == i+1]['energyS5E8'])
    energylistS5E8_I1.append(temp)

In [ ]:
eincome2S3E2 = eincome2[eincome2['resultsS3E2']!='infeasible']
energylistS3E2_I2 = []
for i in range(9):
    temp = np.mean(eincome2S3E2[eincome2S3E2['CENSUS_D'] == i+1]['energyS3E2'])
    energylistS3E2_I2.append(temp)
    
eincome2S3E8 = eincome2[eincome2['resultsS3E8']!='infeasible']
energylistS3E8_I2 = []
for i in range(9):
    temp = np.mean(eincome2S3E8[eincome2S3E8['CENSUS_D'] == i+1]['energyS3E8'])
    energylistS3E8_I2.append(temp)

eincome2S5E2 = eincome2[eincome2['resultsS5E2']!='infeasible']
energylistS5E2_I2 = []
for i in range(9):
    temp = np.mean(eincome2S5E2[eincome2S5E2['CENSUS_D'] == i+1]['energyS5E2'])
    energylistS5E2_I2.append(temp)
     
eincome2S5E8 = eincome2[eincome2['resultsS5E8']!='infeasible']
energylistS5E8_I2 = []
for i in range(9):
    temp = np.mean(eincome2S5E8[eincome2S5E8['CENSUS_D'] == i+1]['energyS5E8'])
    energylistS5E8_I2.append(temp)

In [ ]:
energyIncome = pd.DataFrame()
  
# print(energy)
  
# append columns to an empty DataFrame
energyIncome['Census Division'] = ['New England', 'Middle Atlantic', 'East North Central',
                               'West North Central', 'South Atlantic', 'East South Central',
                               'West South Central', 'Mountain', 'Pacific']

energyIncome['Income 1 (I30E20)'] = energylistS3E2_I0
energyIncome['Income 2 (I30E20)'] = energylistS3E2_I1
energyIncome['Income 3 (I30E20)'] = energylistS3E2_I2

energyIncome['Income 1 (I30E80)'] = energylistS3E8_I0
energyIncome['Income 2 (I30E80)'] = energylistS3E8_I1
energyIncome['Income 3 (I30E80)'] = energylistS3E8_I2

energyIncome['Income 1 (I50E20)'] = energylistS5E2_I0
energyIncome['Income 2 (I50E20)'] = energylistS5E2_I1
energyIncome['Income 3 (I50E20)'] = energylistS5E2_I2

energyIncome['Income 1 (I50E80)'] = energylistS5E8_I0
energyIncome['Income 2 (I50E80)'] = energylistS5E8_I1
energyIncome['Income 3 (I50E80)'] = energylistS5E8_I2

In [ ]:
energyIncome

In [ ]:
ecluster0 = df[df['Cluster_new_features'] == 0]
ecluster1 = df[df['Cluster_new_features'] == 1]
ecluster2 = df[df['Cluster_new_features'] == 2]

In [ ]:
ecluster0S3E2 = ecluster0[ecluster0['resultsS3E2']!='infeasible']
energylistS3E2_C0 = []
for i in range(9):
    temp = np.mean(ecluster0S3E2[ecluster0S3E2['CENSUS_D'] == i+1]['energyS3E2'])
    energylistS3E2_C0.append(temp)
    
ecluster0S3E8 = ecluster0[ecluster0['resultsS3E8']!='infeasible']
energylistS3E8_C0 = []
for i in range(9):
    temp = np.mean(ecluster0S3E8[ecluster0S3E8['CENSUS_D'] == i+1]['energyS3E8'])
    energylistS3E8_C0.append(temp)

ecluster0S5E2 = ecluster0[ecluster0['resultsS5E2']!='infeasible']
energylistS5E2_C0 = []
for i in range(9):
    temp = np.mean(ecluster0S5E2[ecluster0S5E2['CENSUS_D'] == i+1]['energyS5E2'])
    energylistS5E2_C0.append(temp)
     
ecluster0S5E8 = ecluster0[ecluster0['resultsS5E8']!='infeasible']
energylistS5E8_C0 = []
for i in range(9):
    temp = np.mean(ecluster0S5E8[ecluster0S5E8['CENSUS_D'] == i+1]['energyS5E8'])
    energylistS5E8_C0.append(temp)


    
ecluster1S3E2 = ecluster1[ecluster1['resultsS3E2']!='infeasible']
energylistS3E2_C1 = []
for i in range(9):
    temp = np.mean(ecluster1S3E2[ecluster1S3E2['CENSUS_D'] == i+1]['energyS3E2'])
    energylistS3E2_C1.append(temp)
    
ecluster1S3E8 = ecluster1[ecluster1['resultsS3E8']!='infeasible']
energylistS3E8_C1 = []
for i in range(9):
    temp = np.mean(ecluster1S3E8[ecluster1S3E8['CENSUS_D'] == i+1]['energyS3E8'])
    energylistS3E8_C1.append(temp)

ecluster1S5E2 = ecluster1[ecluster1['resultsS5E2']!='infeasible']
energylistS5E2_C1 = []
for i in range(9):
    temp = np.mean(ecluster1S5E2[ecluster1S5E2['CENSUS_D'] == i+1]['energyS5E2'])
    energylistS5E2_C1.append(temp)
     
ecluster1S5E8 = ecluster1[ecluster1['resultsS5E8']!='infeasible']
energylistS5E8_C1 = []
for i in range(9):
    temp = np.mean(ecluster1S5E8[ecluster1S5E8['CENSUS_D'] == i+1]['energyS5E8'])
    energylistS5E8_C1.append(temp)



    
ecluster2S3E2 = ecluster2[ecluster2['resultsS3E2']!='infeasible']
energylistS3E2_C2 = []
for i in range(9):
    temp = np.mean(ecluster2S3E2[ecluster2S3E2['CENSUS_D'] == i+1]['energyS3E2'])
    energylistS3E2_C2.append(temp)
    
ecluster2S3E8 = ecluster2[ecluster2['resultsS3E8']!='infeasible']
energylistS3E8_C2 = []
for i in range(9):
    temp = np.mean(ecluster2S3E8[ecluster2S3E8['CENSUS_D'] == i+1]['energyS3E8'])
    energylistS3E8_C2.append(temp)

ecluster2S5E2 = ecluster2[ecluster2['resultsS5E2']!='infeasible']
energylistS5E2_C2 = []
for i in range(9):
    temp = np.mean(ecluster2S5E2[ecluster2S5E2['CENSUS_D'] == i+1]['energyS5E2'])
    energylistS5E2_C2.append(temp)
     
ecluster2S5E8 = ecluster2[ecluster2['resultsS5E8']!='infeasible']
energylistS5E8_C2 = []
for i in range(9):
    temp = np.mean(ecluster2S5E8[ecluster2S5E8['CENSUS_D'] == i+1]['energyS5E8'])
    energylistS5E8_C2.append(temp)

In [ ]:
    
energyCluster = pd.DataFrame()
  
# print(energy)
  
# append columns to an empty DataFrame
energyCluster['Census Division'] = ['New England', 'Middle Atlantic', 'East North Central',
                               'West North Central', 'South Atlantic', 'East South Central',
                               'West South Central', 'Mountain', 'Pacific']

energyCluster['Cluster 1 (I30E20)'] = energylistS3E2_C0
energyCluster['Cluster 2 (I30E20)'] = energylistS3E2_C1
energyCluster['Cluster 3 (I30E20)'] = energylistS3E2_C2

energyCluster['Cluster 1 (I30E80)'] = energylistS3E8_C0
energyCluster['Cluster 2 (I30E80)'] = energylistS3E8_C1
energyCluster['Cluster 3 (I30E80)'] = energylistS3E8_C2

energyCluster['Cluster 1 (I50E20)'] = energylistS5E2_C0
energyCluster['Cluster 2 (I50E20)'] = energylistS5E2_C1
energyCluster['Cluster 3 (I50E20)'] = energylistS5E2_C2

energyCluster['Cluster 1 (I50E80)'] = energylistS5E8_C0
energyCluster['Cluster 2 (I50E80)'] = energylistS5E8_C1
energyCluster['Cluster 3 (I50E80)'] = energylistS5E8_C2

In [ ]:
energyIncome

In [ ]:
energyCluster

In [ ]:
energyCluster.to_excel("MUDEnergyCluster.xlsx",
...              sheet_name='Energy_Cluster')  
energyIncome.to_excel("MUDEnergyIncome.xlsx",
...              sheet_name='Energy_Income')

In [ ]:
MudShare

In [ ]:

plt.style.use('fivethirtyeight')

x1 = MudShare['Cluster 1 (I30E20)']*100
x2 = MudShare['Cluster 2 (I30E20)']*100
x3 = MudShare['Cluster 3 (I30E20)']*100
x4 = MudShare['Cluster 1 (I30E80)']*100
x5 = MudShare['Cluster 2 (I30E80)']*100
x6 = MudShare['Cluster 3 (I30E80)']*100

y = MudShare['Census Division']
fig = plt.figure(figsize=(10, 8),dpi=300)
# fig(figsize=(8, 6), dpi=80)
ax1 = fig.add_subplot(111)

ax1.scatter(x1, y, s=50, c='b', marker="^", label='C1&S1')
ax1.scatter(x2, y, s=50, c='r', marker="^", label='C2&S1')
ax1.scatter(x3, y, s=50, c='g', marker="^", label='C3&S1')
ax1.scatter(x4, y, s=50, c='b', marker="o", label='C1&S2')
ax1.scatter(x5, y, s=50, c='r', marker="o", label='C2&S2')
ax1.scatter(x6, y, s=50, c='g', marker="o", label='C3&S2')
plt.xlabel("Share (%)")
plt.title('Expected share of MUDs deployment (starting SOC: 30 miles)')
plt.legend(loc='best',prop={'size': 7.2});
# plt.xticks(rotation=45,fontsize=14)
# plt.yticks(fontsize=14)
# plt.xlabel('Time of Day',fontsize=18)
# plt.ylabel('VMT (Miles)',fontsize=18)
# plt.title('MUDs residents VMT during time of day',fontsize=28)
plt.legend(fontsize=18)
plt.show()

fig.savefig('figure8aDiff.png',dpi=300)

In [ ]:
x1 = MudShare['Cluster 1 (I50E20)']*100
x2 = MudShare['Cluster 2 (I50E20)']*100
x3 = MudShare['Cluster 3 (I50E20)']*100
x4 = MudShare['Cluster 1 (I50E80)']*100
x5 = MudShare['Cluster 2 (I50E80)']*100
x6 = MudShare['Cluster 3 (I50E80)']*100

y = MudShare['Census Division']
fig = plt.figure(figsize=(10, 8),dpi=300)
# fig(figsize=(8, 6), dpi=80)
ax1 = fig.add_subplot(111)

ax1.scatter(x1, y, s=50, c='b', marker="^", label='C1&S1')
ax1.scatter(x2, y, s=50, c='r', marker="^", label='C2&S1')
ax1.scatter(x3, y, s=50, c='g', marker="^", label='C3&S1')
ax1.scatter(x4, y, s=50, c='b', marker="o", label='C1&S2')
ax1.scatter(x5, y, s=50, c='r', marker="o", label='C2&S2')
ax1.scatter(x6, y, s=50, c='g', marker="o", label='C3&S2')
plt.xlabel('Share (%)')
plt.title('Expected share of MUDs deployment (starting SOC: 50 miles)')
plt.legend(loc='upper center');
plt.legend(fontsize=18)
plt.show()

fig.savefig('figure8bDiff.png',dpi=300)

In [ ]:
MudShareIncome

In [ ]:
x1 = MudShareIncome['Income 1 (I30E20)']*100
x2 = MudShareIncome['Income 2 (I30E20)']*100
x3 = MudShareIncome['Income 3 (I30E20)']*100
x4 = MudShareIncome['Income 1 (I30E80)']*100
x5 = MudShareIncome['Income 2 (I30E80)']*100
x6 = MudShareIncome['Income 3 (I30E80)']*100

y = MudShareIncome['Census Division']
fig = plt.figure(figsize=(10, 8),dpi=300)
# fig(figsize=(8, 6), dpi=80)
ax1 = fig.add_subplot(111)

ax1.scatter(x1, y, s=50, c='b', marker="^", label='LI&S1')
ax1.scatter(x2, y, s=50, c='r', marker="^", label='MI&S1')
ax1.scatter(x3, y, s=50, c='g', marker="^", label='UI&S1')
ax1.scatter(x4, y, s=50, c='b', marker="o", label='LI&S2')
ax1.scatter(x5, y, s=50, c='r', marker="o", label='MI&S2')
ax1.scatter(x6, y, s=50, c='g', marker="o", label='UI&S2')
plt.xlabel("Share (%)")
plt.title('Expected share of MUDs deployment (starting SOC: 30 mi)')
plt.legend(loc='best',prop={'size': 7.5});
plt.legend(fontsize=18)
plt.show()

fig.savefig('figure8cDiff.png',dpi=300)

In [ ]:
x1 = MudShareIncome['Income 1 (I50E20)']*100
x2 = MudShareIncome['Income 2 (I50E20)']*100
x3 = MudShareIncome['Income 3 (I50E20)']*100
x4 = MudShareIncome['Income 1 (I50E80)']*100
x5 = MudShareIncome['Income 2 (I50E80)']*100
x6 = MudShareIncome['Income 3 (I50E80)']*100

y = MudShareIncome['Census Division']
fig = plt.figure(figsize=(10, 8),dpi=300)
# fig(figsize=(8, 6), dpi=80)
ax1 = fig.add_subplot(111)

ax1.scatter(x1, y, s=50, c='b', marker="^", label='LI&S1')
ax1.scatter(x2, y, s=50, c='r', marker="^", label='MI&S1')
ax1.scatter(x3, y, s=50, c='g', marker="^", label='UI&S1')
ax1.scatter(x4, y, s=50, c='b', marker="o", label='LI&S2')
ax1.scatter(x5, y, s=50, c='r', marker="o", label='MI&S2')
ax1.scatter(x6, y, s=50, c='g', marker="o", label='UI&S2')
plt.xlabel('Share (%)')
plt.title('Expected share of MUDs deployment (starting SOC: 50 mi)')
plt.legend(loc='best');
plt.legend(fontsize=18)
plt.show()

fig.savefig('figure8dDiff.png',dpi=300)

In [ ]:
energyCluster = pd.read_excel('EnergyCluster.xlsx')
energyCluster

In [ ]:
plt.style.use('fivethirtyeight')

x1 = energyCluster['Cluster 1 (I30E20)']*1
x2 = energyCluster['Cluster 2 (I30E20)']*1
x3 = energyCluster['Cluster 3 (I30E20)']*1
x4 = energyCluster['Cluster 1 (I30E80)']*1
x5 = energyCluster['Cluster 2 (I30E80)']*1
x6 = energyCluster['Cluster 3 (I30E80)']*1

y = energyCluster['Census Division']
fig = plt.figure(figsize=(10, 8), dpi=300)
# fig(figsize=(8, 6), dpi=80)
ax1 = fig.add_subplot(111)

ax1.scatter(x1, y, s=50, c='b', marker="^", label='C1&S1')
ax1.scatter(x2, y, s=50, c='r', marker="^", label='C2&S1')
ax1.scatter(x3, y, s=50, c='g', marker="^", label='C3&S1')
ax1.scatter(x4, y, s=50, c='b', marker="o", label='C1&S2')
ax1.scatter(x5, y, s=50, c='r', marker="o", label='C2&S2')
ax1.scatter(x6, y, s=50, c='g', marker="o", label='C3&S2')
plt.xlabel("Electricity & Energy (kWh)")
# plt.ylabel("Y axis label")
plt.title('Per vehicle energy use daily (starting SOC: 30 miles)')
plt.legend(loc='best',prop={'size': 7.5});
plt.legend(fontsize=18)
plt.show()

fig.savefig('figure9aDiffTotal.png',dpi=300)

In [ ]:
x1 = energyCluster['Cluster 1 (I50E20)']*1
x2 = energyCluster['Cluster 2 (I50E20)']*1
x3 = energyCluster['Cluster 3 (I50E20)']*1
x4 = energyCluster['Cluster 1 (I50E80)']*1
x5 = energyCluster['Cluster 2 (I50E80)']*1
x6 = energyCluster['Cluster 3 (I50E80)']*1

y = energyCluster['Census Division']
fig = plt.figure(figsize=(10, 8), dpi=300)
# fig(figsize=(8, 6), dpi=80)
ax1 = fig.add_subplot(111)

ax1.scatter(x1, y, s=50, c='b', marker="^", label='C1&S1')
ax1.scatter(x2, y, s=50, c='r', marker="^", label='C2&S1')
ax1.scatter(x3, y, s=50, c='g', marker="^", label='C3&S1')
ax1.scatter(x4, y, s=50, c='b', marker="o", label='C1&S2')
ax1.scatter(x5, y, s=50, c='r', marker="o", label='C2&S2')
ax1.scatter(x6, y, s=50, c='g', marker="o", label='C3&S2')
plt.xlabel("Electricity & Energy (KWh)")
# plt.ylabel("Y axis label")
plt.title('Per vehicle energy use daily (starting SOC: 50 miles)')
plt.legend(loc='upper center',prop={'size': 7.5});
plt.legend(fontsize=18)
plt.show()

fig.savefig('figure9bDiffTotal.png',dpi=300)

In [ ]:
energyIncome = pd.read_excel('EnergyIncome.xlsx')
energyIncome

In [ ]:
x1 = energyIncome['Income 1 (I30E20)']*1
x2 = energyIncome['Income 2 (I30E20)']*1
x3 = energyIncome['Income 3 (I30E20)']*1
x4 = energyIncome['Income 1 (I30E80)']*1
x5 = energyIncome['Income 2 (I30E80)']*1
x6 = energyIncome['Income 3 (I30E80)']*1

y = energyIncome['Census Division']
fig = plt.figure(figsize=(10, 8), dpi=300)
# fig(figsize=(8, 6), dpi=80)
ax1 = fig.add_subplot(111)

ax1.scatter(x1, y, s=50, c='b', marker="^", label='LI&S1')
ax1.scatter(x2, y, s=50, c='r', marker="^", label='MI&S1')
ax1.scatter(x3, y, s=50, c='g', marker="^", label='UI&S1')
ax1.scatter(x4, y, s=50, c='b', marker="o", label='LI&S2')
ax1.scatter(x5, y, s=50, c='r', marker="o", label='MI&S2')
ax1.scatter(x6, y, s=50, c='g', marker="o", label='UI&S2')
plt.xlabel("Electricity & Energy (KWh)")
# plt.ylabel("Y axis label")
plt.title('Per vehicle energy use daily of income classes (starting SOC: 30 miles)')
plt.legend(loc='best',prop={'size': 7.5});
plt.legend(fontsize=18)
plt.show()

fig.savefig('figure9cDiffTotal.png',dpi=300)

In [ ]:
x1 = energyIncome['Income 1 (I50E20)']*1
x2 = energyIncome['Income 2 (I50E20)']*1
x3 = energyIncome['Income 3 (I50E20)']*1
x4 = energyIncome['Income 1 (I50E80)']*1
x5 = energyIncome['Income 2 (I50E80)']*1
x6 = energyIncome['Income 3 (I50E80)']*1

y = energyIncome['Census Division']
fig = plt.figure(figsize=(10, 8), dpi=300)
# fig(figsize=(8, 6), dpi=80)
ax1 = fig.add_subplot(111)

ax1.scatter(x1, y, s=50, c='b', marker="^", label='LI&S1')
ax1.scatter(x2, y, s=50, c='r', marker="^", label='MI&S1')
ax1.scatter(x3, y, s=50, c='g', marker="^", label='UI&S1')
ax1.scatter(x4, y, s=50, c='b', marker="o", label='LI&S2')
ax1.scatter(x5, y, s=50, c='r', marker="o", label='MI&S2')
ax1.scatter(x6, y, s=50, c='g', marker="o", label='UI&S2')
plt.xlabel("Electricity & Energy (KWh)")
# plt.ylabel("Y axis label")
plt.title('Per vehicle energy use daily of income classes (starting SOC: 50 miles)')
plt.legend(loc='upper right',prop={'size': 7.5});
plt.legend(fontsize=18)
plt.show()

fig.savefig('figure9dDiffTotal.png',dpi=300)